[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["flooder"]

[project]
name = "flooder"
version = "1.0.2"
description = "Flood complex PH"
readme = "README.md"
license = "MIT"
authors = [{ name="Paolo Pellizzoni, Florian Graf, Martin Uray, Stefan Huber, Roland Kwitt", email="roland.kwitt@gmail.com" }]
dependencies = [
    "torch",
    "gudhi",
    "numpy",
    "gdown",
    "zstandard",
    "tqdm",
    "pandas",
    "fpsample",
    "scipy",
    "rich",
    "rich_argparse",
    "pyyaml",
    "gdown",
    "zstandard",
]
requires-python = ">=3.8"

[project.scripts]
flooder = "flooder.cli:main"